### ISSUE TITLE
训练文本检测数据集TotalText，模型不收敛

### ISSUE THREAD

**Issue by ychensu** [flytocc/mmdetection#1]
在22个epoch左右，map会急剧下降，去除PhotoMetricDistortion、Expand、MinIoURandomCrop、RandomFlip等数据增强后仍存在该问题。将学习率调整为1e-5后，在50个epoch左右，map会急剧下降。

**Comment by ychensu** [comment]
数据集：链接：https://pan.baidu.com/s/10quWTHHq1NR9Ra0zwsP58g?pwd=72ty 
提取码：72ty 。   config中num_classs从80改成了1。

**Comment by flytocc** [comment]
代码你是怎么改的

**Comment by flytocc** [comment]
> 在22个epoch左右，map会急剧下降，去除PhotoMetricDistortion、Expand、MinIoURandomCrop、RandomFlip等数据增强后仍存在该问题。将学习率调整为1e-5后，在50个epoch左右，map会急剧下降。

会不会是过拟合了

**Comment by ychensu** [comment]
> > 在22个epoch左右，map会急剧下降，去除PhotoMetricDistortion、Expand、MinIoURandomCrop、RandomFlip等数据增强后仍存在该问题。将学习率调整为1e-5后，在50个epoch左右，map会急剧下降。
> 
> 会不会是过拟合了

都没收敛谈不上过拟合，rt-detr官方pytorch源码是能收敛的，mmdet里的deformable detr或者dino一样都能收敛，唯独您的rt-detr不能。

**Comment by flytocc** [comment]
有代码和log吗

**Comment by ychensu** [comment]
> 代码你是怎么改的

1)configs/rtdetr/rtdetr_r50vd_8xb2-72e_coco.py中的num_classes改成了1；2）/remote-home/suyuchen/code/mmdetection-rtdetr/configs/_base_/datasets/coco_detection.py路径改成了        ann_file='totaltext_train.json',
        data_prefix=dict(img='imgs/training/'),         ann_file='totaltext_test.json',
        data_prefix=dict(img='imgs/')，； 3）mmdet/datasets/coco.py中类别及颜色修改如下：class CocoDataset(BaseDetDataset):
    """Dataset for COCO."""

    METAINFO = {
        'classes':
        ('text',),
        # palette is a list of color tuples, which is used for visualization.
        'palette':
        [(220, 20, 60),]
    }

**Comment by flytocc** [comment]
启动命令呢，我有空测试一下

**Comment by ychensu** [comment]
[20240220_030315.log](https://github.com/flytocc/mmdetection/files/14355498/20240220_030315.log)
[20240220_040327.log](https://github.com/flytocc/mmdetection/files/14355504/20240220_040327.log)
[20240220_045555.log](https://github.com/flytocc/mmdetection/files/14355505/20240220_045555.log)

**Comment by ychensu** [comment]
> 启动命令呢，我有空测试一下

   ./tools/dist_train.sh configs/rtdetr/rtdetr_r50vd_8xb2-72e_coco.py 4   拜托大佬了

**Comment by flytocc** [comment]
> 都没收敛谈不上过拟合，rt-detr官方pytorch源码是能收敛的，mmdet里的deformable detr或者dino一样都能收敛，唯独您的rt-detr不能。

有rt-detr官方pytorch的训练log吗？最后精度大概多少？

**Comment by ychensu** [comment]
> > 都没收敛谈不上过拟合，rt-detr官方pytorch源码是能收敛的，mmdet里的deformable detr或者dino一样都能收敛，唯独您的rt-detr不能。
> 
> 有rt-detr官方pytorch的训练log吗？最后精度大概多少？

[20240221_071605.log](https://github.com/flytocc/mmdetection/files/14356085/20240221_071605.log)
这是我刚用仓库中的dino模型训练的结果，可以看到是能收敛的，训练命令是./tools/dist_train.sh ./configs/dino/dino-4scale_r50_8xb2-36e_coco.py  8。  我记得rt-detr官方pytorch最终的map有56左右，log删了，我现在重新训一下再发给您

**Comment by ychensu** [comment]
> > > 都没收敛谈不上过拟合，rt-detr官方pytorch源码是能收敛的，mmdet里的deformable detr或者dino一样都能收敛，唯独您的rt-detr不能。
> > 
> > 
> > 有rt-detr官方pytorch的训练log吗？最后精度大概多少？
> 
> [20240221_071605.log](https://github.com/flytocc/mmdetection/files/14356085/20240221_071605.log) 这是我刚用仓库中的dino模型训练的结果，可以看到是能收敛的，训练命令是./tools/dist_train.sh ./configs/dino/dino-4scale_r50_8xb2-36e_coco.py 8。 我记得rt-detr官方pytorch最终的map有56左右，log删了，我现在重新训一下再发给您

[rt-detr.txt](https://github.com/flytocc/mmdetection/files/14358083/rt-detr.txt)
这是rt-detr的官方源码，同样是仅改了num_classes和数据集路径，map有56，请您过目。

**Comment by flytocc** [comment]
太客气啦。方便本repo上试试用coco权重做初始化训练吗

不知道是不是初始化的问题

**Comment by ychensu** [comment]
> 太客气啦。方便本repo上试试用coco权重做初始化训练吗
> 
> 不知道是不是初始化的问题

请问是用哪个coco权重做初始化训练呢，是训练您写的rt-detr嘛，感觉前20个epoch能收敛，应该不是初始化权重的问题

**Comment by ychensu** [comment]
> 太客气啦。方便本repo上试试用coco权重做初始化训练吗
> 
> 不知道是不是初始化的问题

[20240221_170146.log](https://github.com/flytocc/mmdetection/files/14367349/20240221_170146.log)
已d大致解决，是环境的问题，用pytorch1.9环境会不收敛，当与rt-detr环境保持一致（pytorch2.0）就能收敛。但还存在前期收敛过慢，后期map与官方源码差1个点的问题（均采用4卡4batch训练）

**Comment by flytocc** [comment]
> [20240221_170146.log](https://github.com/flytocc/mmdetection/files/14367349/20240221_170146.log) 已d大致解决，是环境的问题，用pytorch1.9环境会不收敛，当与rt-detr环境保持一致（pytorch2.0）就能收敛。但还存在前期收敛过慢，后期map与官方源码差1个点的问题（均采用4卡4batch训练）

把warnup去掉试试

**Comment by ychensu** [comment]
> > [20240221_170146.log](https://github.com/flytocc/mmdetection/files/14367349/20240221_170146.log) 已d大致解决，是环境的问题，用pytorch1.9环境会不收敛，当与rt-detr环境保持一致（pytorch2.0）就能收敛。但还存在前期收敛过慢，后期map与官方源码差1个点的问题（均采用4卡4batch训练）
> 
> 把warnup去掉试试

好的，感谢指点。

**Comment by ychensu** [comment]
> > > [20240221_170146.log](https://github.com/flytocc/mmdetection/files/14367349/20240221_170146.log) 已d大致解决，是环境的问题，用pytorch1.9环境会不收敛，当与rt-detr环境保持一致（pytorch2.0）就能收敛。但还存在前期收敛过慢，后期map与官方源码差1个点的问题（均采用4卡4batch训练）
> > 
> > 
> > 把warnup去掉试试
> 
> 好的，感谢指点。

[20240222_055111.log](https://github.com/flytocc/mmdetection/files/14371840/20240222_055111.log)
大佬您好，按您的指点，我去掉了warmup，前期收敛的确更快了，但是这并不影响中后期的性能，和rt-detr官方源码相比还是低了1个点左右（环境相同），感觉还是训练策略或者数据增强的问题

**Comment by flytocc** [comment]
> [20240222_055111.log](https://github.com/flytocc/mmdetection/files/14371840/20240222_055111.log) 大佬您好，按您的指点，我去掉了warmup，前期收敛的确更快了，但是这并不影响中后期的性能，和rt-detr官方源码相比还是低了1个点左右（环境相同），感觉还是训练策略或者数据增强的问题

可以试试这个分支吗 https://github.com/flytocc/mmdetection/tree/rtdetr-patch

**Comment by ychensu** [comment]
> > [20240222_055111.log](https://github.com/flytocc/mmdetection/files/14371840/20240222_055111.log) 大佬您好，按您的指点，我去掉了warmup，前期收敛的确更快了，但是这并不影响中后期的性能，和rt-detr官方源码相比还是低了1个点左右（环境相同），感觉还是训练策略或者数据增强的问题
> 
> 可以试试这个分支吗 https://github.com/flytocc/mmdetection/tree/rtdetr-patch

[20240222_162844.log](https://github.com/flytocc/mmdetection/files/14380875/20240222_162844.log)
和之前的几乎没有变化，还是差了官方源码1个点左右

**Comment by flytocc** [comment]
> [20240222_162844.log](https://github.com/flytocc/mmdetection/files/14380875/20240222_162844.log) 和之前的几乎没有变化，还是差了官方源码1个点左右

我又更新了一些代码，试着训练了一次，best mAP56.4

这是config：
```
_base_ = './rtdetr_r50vd_8xb2-72e_coco.py'

model = dict(bbox_head=dict(num_classes=1))

param_scheduler = None

data_root = 'data/totaltext/'
metainfo = dict(classes=('text', ))

train_dataloader = dict(
    pin_memory=True,
    use_multi_epochs_loader=True,
    dataset=dict(
        metainfo=metainfo,
        data_root=data_root,
        ann_file='totaltext_train.json',
        data_prefix=dict(img='imgs/training/')))
val_dataloader = dict(
    dataset=dict(
        metainfo=metainfo,
        data_root=data_root,
        ann_file='totaltext_test.json',
        data_prefix=dict(img='imgs/')))
test_dataloader = val_dataloader

val_evaluator = dict(ann_file=data_root + 'totaltext_test.json')
test_evaluator = val_evaluator
```

**Comment by mstd-jie** [comment]
> > [20240222_162844.log](https://github.com/flytocc/mmdetection/files/14380875/20240222_162844.log) 和之前的几乎没有变化，还是差了官方源码1个点左右
> 
> 我又更新了一些代码，试着训练了一次，best mAP56.4
> 
> 这是config：
> 
> ```
> _base_ = './rtdetr_r50vd_8xb2-72e_coco.py'
> 
> model = dict(bbox_head=dict(num_classes=1))
> 
> param_scheduler = None
> 
> data_root = 'data/totaltext/'
> metainfo = dict(classes=('text', ))
> 
> train_dataloader = dict(
>     pin_memory=True,
>     use_multi_epochs_loader=True,
>     dataset=dict(
>         metainfo=metainfo,
>         data_root=data_root,
>         ann_file='totaltext_train.json',
>         data_prefix=dict(img='imgs/training/')))
> val_dataloader = dict(
>     dataset=dict(
>         metainfo=metainfo,
>         data_root=data_root,
>         ann_file='totaltext_test.json',
>         data_prefix=dict(img='imgs/')))
> test_dataloader = val_dataloader
> 
> val_evaluator = dict(ann_file=data_root + 'totaltext_test.json')
> test_evaluator = val_evaluator
> ```

牛哇老哥，能否加个v呀。
